# print("abc abc".capitalize())
# print("abc abc".title())
# s="hello hello"
# print(len(s))
# print(s.count("l",5,11))
# print('Abcdd'>'abc')
# print(ord('A'))
# print(ord('a'))
# print(chr(111))
str='welcome to magicland'
print(str.find('t'))
print(str.startswith('welcome'))
print(str.endswith('magicland'))
print(str.index('magicland'))
print(str.upper())